// 琳宝私厨 · 菜品元数据（图片 + 营养信息 + 难度/耗时）
// 热量为一人份估算值，仅供娱乐参考，非医学建议
// difficulty: 简单 / 中等 / 较难；time: 预计耗时（分钟），均为估算
module.exports = {
  META: [
    // ===== 带图菜（原有 12 道，已全部换成真实美食照片） =====
    { name: "虾仁滑蛋吐司", image: "/assets/dishes/ai-shrimp-toast.jpg", kcal: 420, benefit: "虾仁低脂高蛋白，加蛋更扛饿，元气满满的一天", nutritionTags: ["高蛋白", "低脂", "元气早餐"], difficulty: "简单", time: 15 },
    { name: "豆乳燕麦杯", image: "/assets/dishes/ai-oat-cup.jpg", kcal: 280, benefit: "燕麦膳食纤维丰富，豆乳温和，代餐好选择", nutritionTags: ["膳食纤维", "饱腹", "低脂"], difficulty: "简单", time: 10 },
    { name: "牛油果鸡蛋贝果", image: "/assets/dishes/ai-bagel.jpg", kcal: 450, benefit: "牛油果富含健康脂肪，配鸡蛋优质蛋白，扛饿又营养", nutritionTags: ["优质脂肪", "高蛋白", "抗饿"], difficulty: "简单", time: 15 },
    { name: "番茄牛腩饭", image: "/assets/dishes/ai-beef-rice.jpg", kcal: 520, benefit: "牛腩补铁补蛋白，番茄维C丰富，暖胃又下饭", nutritionTags: ["高蛋白", "补铁", "暖胃"], difficulty: "中等", time: 90 },
    { name: "照烧鸡腿饭", image: "/assets/dishes/ai-chicken-rice.jpg", kcal: 480, benefit: "鸡腿肉优质蛋白，照烧汁咸甜开胃，吃饱又有劲", nutritionTags: ["高蛋白", "开胃", "饱腹"], difficulty: "中等", time: 40 },
    { name: "鲜虾云吞面", image: "/assets/dishes/ai-wonton-noodle.jpg", kcal: 430, benefit: "虾仁低脂高蛋白，云吞面暖胃管饱", nutritionTags: ["高蛋白", "暖胃", "饱腹"], difficulty: "中等", time: 40 },
    { name: "芝士牛肉汉堡", image: "/assets/dishes/ai-burger.jpg", kcal: 560, benefit: "牛肉补铁补蛋白，芝士补钙，饱腹感强", nutritionTags: ["高蛋白", "补铁", "补钙"], difficulty: "中等", time: 30 },
    { name: "蒜香黄油意面", image: "/assets/dishes/ai-pasta.jpg", kcal: 520, benefit: "意面提供充足碳水能量，蒜香开胃", nutritionTags: ["能量", "开胃"], difficulty: "简单", time: 25 },
    { name: "寿喜烧双人锅", image: "/assets/dishes/ai-sukiyaki.jpg", kcal: 320, benefit: "牛肉蔬菜一锅炖，蛋白蔬菜双丰收，暖身又治愈（一人份）", nutritionTags: ["高蛋白", "蔬菜多", "暖身"], difficulty: "简单", time: 25 },
    { name: "脆皮炸鸡拼盘", image: "/assets/dishes/ai-fried-chicken.jpg", kcal: 620, benefit: "热量偏高，解馋可以，吃完多走走哦", nutritionTags: ["解馋", "高热量"], difficulty: "中等", time: 40 },
    { name: "热辣小龙虾", image: "/assets/dishes/ai-crayfish.jpg", kcal: 350, benefit: "虾肉低脂高蛋白，麻辣过瘾", nutritionTags: ["高蛋白", "低脂", "麻辣"], difficulty: "较难", time: 60 },
    { name: "草莓奶油松饼", image: "/assets/dishes/ai-pancake.jpg", kcal: 480, benefit: "草莓维C丰富，松饼甜软，偶尔放纵一下", nutritionTags: ["甜品", "维C"], difficulty: "简单", time: 30 },

    // ===== 内置菜谱 47 道（AI 配图） =====
    { name: "宫保鸡丁", image: "/assets/dishes/ai-gongbao-jiding.jpg", kcal: 350, benefit: "鸡肉高蛋白低脂肪，酸甜微辣开胃下饭", nutritionTags: ["高蛋白", "开胃", "下饭"], difficulty: "中等", time: 30 },
    { name: "麻婆豆腐", image: "/assets/dishes/ai-mapo-tofu.jpg", kcal: 280, benefit: "豆腐植物蛋白丰富，麻辣开胃，素食友好", nutritionTags: ["植物蛋白", "开胃", "下饭"], difficulty: "简单", time: 20 },
    { name: "鱼香肉丝", image: "/assets/dishes/ai-yuxiang-rousi.jpg", kcal: 320, benefit: "荤素搭配，酸甜咸辣俱全，经典下饭", nutritionTags: ["高蛋白", "下饭"], difficulty: "中等", time: 30 },
    { name: "白灼虾", image: "/assets/dishes/ai-baizhuo-xia.jpg", kcal: 180, benefit: "最大程度保留鲜味，虾肉低脂高蛋白", nutritionTags: ["高蛋白", "低脂", "减脂友好"], difficulty: "简单", time: 15 },
    { name: "清蒸鲈鱼", image: "/assets/dishes/ai-qingzheng-luyu.jpg", kcal: 200, benefit: "鱼肉细嫩易消化，富含优质蛋白和DHA", nutritionTags: ["高蛋白", "易消化", "补脑"], difficulty: "中等", time: 25 },
    { name: "番茄炒蛋", image: "/assets/dishes/ai-fanqie-chaodan.jpg", kcal: 220, benefit: "番茄维C加鸡蛋蛋白，酸甜下饭，家常顶配", nutritionTags: ["维C", "高蛋白", "下饭"], difficulty: "简单", time: 10 },
    { name: "土豆丝炒肉", image: "/assets/dishes/ai-tudou-rousi.jpg", kcal: 300, benefit: "碳水加蛋白，家常暖胃", nutritionTags: ["饱腹", "下饭"], difficulty: "简单", time: 20 },
    { name: "红烧肉", image: "/assets/dishes/ai-hongshao-rou.jpg", kcal: 480, benefit: "软糯入味，热量偏高，偶尔解馋", nutritionTags: ["解馋", "高热量"], difficulty: "较难", time: 90 },
    { name: "蒜蓉生菜", image: "/assets/dishes/ai-suan-rong-shengcai.jpg", kcal: 120, benefit: "低卡高纤维，清爽解腻", nutritionTags: ["低卡", "高纤维", "解腻"], difficulty: "简单", time: 8 },
    { name: "干煸四季豆", image: "/assets/dishes/ai-ganbian-sijidou.jpg", kcal: 180, benefit: "四季豆富含膳食纤维，干煸咸香下饭", nutritionTags: ["高纤维", "下饭"], difficulty: "中等", time: 25 },
    { name: "地三鲜", image: "/assets/dishes/ai-ditsanxian.jpg", kcal: 260, benefit: "茄子土豆青椒三鲜，素食下饭", nutritionTags: ["素食", "下饭", "高纤维"], difficulty: "中等", time: 30 },
    { name: "西红柿鸡蛋汤", image: "/assets/dishes/ai-xihongshi-jidan-tang.jpg", kcal: 90, benefit: "低卡暖胃，番茄维C丰富", nutritionTags: ["低卡", "维C", "暖胃"], difficulty: "简单", time: 15 },
    { name: "紫菜蛋花汤", image: "/assets/dishes/ai-zicai-dan-tang.jpg", kcal: 70, benefit: "紫菜含碘和膳食纤维，低卡鲜香", nutritionTags: ["低卡", "含碘", "鲜香"], difficulty: "简单", time: 10 },
    { name: "玉米排骨汤", image: "/assets/dishes/ai-yumi-paigu-tang.jpg", kcal: 260, benefit: "玉米粗粮加排骨蛋白，汤鲜滋补", nutritionTags: ["高蛋白", "滋补", "暖胃"], difficulty: "中等", time: 90 },
    { name: "黄金蛋炒饭", image: "/assets/dishes/ai-dan-chao-fan.jpg", kcal: 450, benefit: "碳水能量足，蛋香浓郁，管饱", nutritionTags: ["饱腹", "能量"], difficulty: "简单", time: 15 },
    { name: "家常炒面", image: "/assets/dishes/ai-jiachang-chaomian.jpg", kcal: 420, benefit: "主食碳水，青菜鸡蛋营养均衡", nutritionTags: ["饱腹", "均衡"], difficulty: "简单", time: 20 },
    { name: "黑椒培根意面", image: "/assets/dishes/ai-heijiao-yimian.jpg", kcal: 480, benefit: "意面碳水供能，黑椒咸香开胃", nutritionTags: ["能量", "开胃"], difficulty: "简单", time: 25 },
    { name: "香煎黄油薯角", image: "/assets/dishes/ai-huangyou-shujiao.jpg", kcal: 260, benefit: "外酥里糯，碳水小食", nutritionTags: ["小食", "饱腹"], difficulty: "简单", time: 25 },
    { name: "板栗烧鸡", image: "/assets/dishes/ai-banli-shaoji.jpg", kcal: 420, benefit: "板栗碳水加鸡肉蛋白，秋冬暖身", nutritionTags: ["高蛋白", "暖身"], difficulty: "中等", time: 60 },
    { name: "芒果班戟", image: "/assets/dishes/ai-mango-banji.jpg", kcal: 330, benefit: "芒果维C丰富，奶油甜软，甜品快乐", nutritionTags: ["甜品", "维C"], difficulty: "简单", time: 30 },
    { name: "木糠杯", image: "/assets/dishes/ai-muxi-bei.jpg", kcal: 280, benefit: "层层奶香，解馋小甜点", nutritionTags: ["甜品", "解馋"], difficulty: "简单", time: 20 },
    { name: "可乐鸡翅", image: "/assets/dishes/ai-kele-jichi.jpg", kcal: 340, benefit: "鸡翅高蛋白，可乐汁咸甜，孩子也爱", nutritionTags: ["高蛋白", "开胃"], difficulty: "简单", time: 40 },
    { name: "青椒肉丝", image: "/assets/dishes/ai-qingjiao-rousi.jpg", kcal: 280, benefit: "青椒维C丰富加瘦肉蛋白，清爽下饭", nutritionTags: ["维C", "高蛋白", "下饭"], difficulty: "简单", time: 20 },
    { name: "酸辣土豆丝", image: "/assets/dishes/ai-suanla-tudousi.jpg", kcal: 180, benefit: "酸辣开胃，低脂爽口", nutritionTags: ["开胃", "低脂"], difficulty: "简单", time: 15 },
    { name: "醋溜白菜", image: "/assets/dishes/ai-gualian-baicai.jpg", kcal: 110, benefit: "白菜高纤维低卡，醋溜开胃", nutritionTags: ["低卡", "高纤维", "开胃"], difficulty: "简单", time: 15 },
    { name: "番茄炖牛腩", image: "/assets/dishes/ai-xihongshi-niunan.jpg", kcal: 420, benefit: "牛腩补铁补蛋白，番茄汤浓郁暖胃", nutritionTags: ["补铁", "高蛋白", "暖胃"], difficulty: "较难", time: 90 },
    { name: "糖醋排骨", image: "/assets/dishes/ai-dezhou-paigu.jpg", kcal: 420, benefit: "排骨补钙补蛋白，糖醋下饭", nutritionTags: ["补钙", "高蛋白", "下饭"], difficulty: "中等", time: 60 },
    { name: "手撕包菜", image: "/assets/dishes/ai-shousi-baocai.jpg", kcal: 130, benefit: "包菜高纤维低卡，干香爽脆", nutritionTags: ["低卡", "高纤维"], difficulty: "简单", time: 15 },
    { name: "辣子鸡丁", image: "/assets/dishes/ai-lazi-jiding.jpg", kcal: 380, benefit: "鸡丁蛋白加辣椒开胃，麻辣过瘾", nutritionTags: ["高蛋白", "开胃", "麻辣"], difficulty: "中等", time: 30 },
    { name: "水煮肉片", image: "/assets/dishes/ai-shuizhu-roupian.jpg", kcal: 400, benefit: "肉片蛋白丰富，麻辣过瘾，下饭", nutritionTags: ["高蛋白", "开胃", "麻辣"], difficulty: "中等", time: 40 },
    { name: "锅包肉", image: "/assets/dishes/ai-guobao-rou.jpg", kcal: 460, benefit: "外酥里嫩，酸甜口，热量偏高", nutritionTags: ["解馋", "高热量"], difficulty: "较难", time: 45 },
    { name: "东北乱炖", image: "/assets/dishes/ai-disanxian-dongbei.jpg", kcal: 380, benefit: "多种蔬菜加排骨，营养全面", nutritionTags: ["高纤维", "高蛋白", "暖胃"], difficulty: "中等", time: 60 },
    { name: "猪肉白菜炖粉条", image: "/assets/dishes/ai-baicai-dunfentiao.jpg", kcal: 400, benefit: "白菜粉条暖胃管饱，东北家常味", nutritionTags: ["暖胃", "饱腹"], difficulty: "中等", time: 50 },
    { name: "剁椒鱼头", image: "/assets/dishes/ai-duojiao-yutou.jpg", kcal: 260, benefit: "鱼头富含胶原蛋白，剁椒开胃", nutritionTags: ["胶原蛋白", "开胃"], difficulty: "中等", time: 40 },
    { name: "农家小炒肉", image: "/assets/dishes/ai-nongjia-xiaochao.jpg", kcal: 380, benefit: "五花肉加青椒，香辣下饭", nutritionTags: ["下饭", "香辣"], difficulty: "简单", time: 20 },
    { name: "家常豆腐", image: "/assets/dishes/ai-bacai-doufu.jpg", kcal: 240, benefit: "豆腐植物蛋白，煎香入味", nutritionTags: ["植物蛋白", "下饭"], difficulty: "简单", time: 20 },
    { name: "蒜蓉西兰花", image: "/assets/dishes/ai-qingchao-xilanhua.jpg", kcal: 140, benefit: "西兰花高纤维高维C，低卡营养", nutritionTags: ["低卡", "高纤维", "维C"], difficulty: "简单", time: 10 },
    { name: "干锅花菜", image: "/assets/dishes/ai-ganguo-huacai.jpg", kcal: 220, benefit: "花菜膳食纤维丰富，干锅焦香", nutritionTags: ["高纤维", "下饭"], difficulty: "中等", time: 25 },
    { name: "凉拌黄瓜", image: "/assets/dishes/ai-liangban-huanggua.jpg", kcal: 80, benefit: "黄瓜低卡水分足，爽口解腻", nutritionTags: ["低卡", "解腻", "清爽"], difficulty: "简单", time: 10 },
    { name: "凉拌木耳", image: "/assets/dishes/ai-liangban-muer.jpg", kcal: 100, benefit: "木耳高纤维，爽脆开胃，低卡", nutritionTags: ["高纤维", "低卡", "开胃"], difficulty: "简单", time: 10 },
    { name: "口水鸡", image: "/assets/dishes/ai-kaoleng-pai.jpg", kcal: 320, benefit: "鸡肉高蛋白，红油香辣开胃", nutritionTags: ["高蛋白", "开胃"], difficulty: "中等", time: 60 },
    { name: "南瓜小米粥", image: "/assets/dishes/ai-xiaomi-zhou.jpg", kcal: 160, benefit: "南瓜胡萝卜素加小米养胃，软糯好消化", nutritionTags: ["养胃", "易消化"], difficulty: "简单", time: 40 },
    { name: "鸡蛋灌饼", image: "/assets/dishes/ai-jianbing-jidan.jpg", kcal: 380, benefit: "鸡蛋蛋白加碳水，早餐扛饿", nutritionTags: ["高蛋白", "早餐", "饱腹"], difficulty: "中等", time: 30 },
    { name: "元气三明治", image: "/assets/dishes/ai-huotui-sanmingzhi.jpg", kcal: 350, benefit: "面包蛋白加蔬菜，营养均衡早餐", nutritionTags: ["高蛋白", "均衡", "早餐"], difficulty: "简单", time: 10 },
    { name: "啤酒鸭", image: "/assets/dishes/ai-pijiu-ya.jpg", kcal: 380, benefit: "鸭肉蛋白丰富，啤酒去腥增香", nutritionTags: ["高蛋白", "开胃"], difficulty: "中等", time: 60 },
    { name: "皮蛋瘦肉粥", image: "/assets/dishes/ai-baozi-doujiang.jpg", kcal: 220, benefit: "米粥养胃好消化，皮蛋瘦肉提鲜", nutritionTags: ["养胃", "易消化"], difficulty: "简单", time: 30 },
    { name: "菠萝咕咾肉", image: "/assets/dishes/ai-tang-cu-liji.jpg", kcal: 420, benefit: "菠萝维C加猪肉蛋白，酸甜开胃", nutritionTags: ["维C", "高蛋白", "开胃"], difficulty: "中等", time: 40 }
  ]
};
