// 钱老板私人定制 - 菜品数据

const CUISINES = [
  { key: 'all', name: '全部', emoji: '🍽️' },
  { key: '川菜', name: '川菜', emoji: '🌶️' },
  { key: '粤菜', name: '粤菜', emoji: '🦐' },
  { key: '湘菜', name: '湘菜', emoji: '🥵' },
  { key: '东北菜', name: '东北菜', emoji: '🥟' },
  { key: '家常菜', name: '家常菜', emoji: '🏠' },
  { key: '西餐', name: '西餐', emoji: '🍝' },
  { key: '汤羹', name: '汤羹', emoji: '🍲' },
  { key: '甜点', name: '甜点', emoji: '🍰' },
];

const CATEGORIES = [
  { key: 'all', name: '全部', emoji: '🍴' },
  { key: '荤菜', name: '荤菜', emoji: '🍖' },
  { key: '素菜', name: '素菜', emoji: '🥬' },
  { key: '汤品', name: '汤品', emoji: '🥣' },
  { key: '主食', name: '主食', emoji: '🍚' },
  { key: '凉菜', name: '凉菜', emoji: '🥗' },
  { key: '早餐', name: '早餐', emoji: '🥪' },
  { key: '甜点', name: '甜点', emoji: '🧁' },
];

// 新增/编辑菜谱时可选的图标
const EMOJI_CHOICES = [
  '🍗', '🌶️', '🥢', '🦐', '🐟', '🍅', '🥔', '🥩', '🥬', '🫛',
  '🍆', '🍲', '🥣', '🌽', '🍚', '🍜', '🍝', '🍟', '🌰', '🥭',
  '🍮', '🍯', '🍳', '🍱', '🍛', '🍤', '🥗', '🥘', '🫕', '🍰',
  '🧁', '🍦', '🥟', '🥡', '🍙', '🍢', '🍡', '🧀', '🥓', '🍖',
];

// 下单成功后随机出现的甜蜜短句
const SWEET_PHRASES = [
  '收到啦，琳宝这就为你下厨 ❤',
  '你点的菜，是我最爱做的菜 🥰',
  '今天也要乖乖吃饭，吃饱饱才有力气想我 😘',
  '为你做饭，是我每天最开心的事 🍳',
  '菜马上就好，先亲一个垫垫肚子 💋',
  '你负责美美哒，做饭交给我就好 ❤',
  '这顿饭里，全是我对你的喜欢 🍲',
  '等我把爱意都炒进这道菜里 🔥',
  '能给你做饭的每一天，都很幸福 🌷',
  '点得好，我家宝贝最有眼光啦 ✨',
  '饭做好了第一个端给你，永远的 VIP 🎀',
  '愿这一餐，温暖你的胃也甜了你的心 🍰',
];

const RECIPES = [
  {
    id: 'gongbao-jiding', name: '宫保鸡丁', emoji: '🍗', cuisine: '川菜', category: '荤菜',
    difficulty: '中等', time: 25, desc: '酸甜微辣，鸡肉嫩滑，花生香脆，超级下饭。',
    tags: ['鸡肉', '花生', '黄瓜', '葱', '干辣椒'],
    ingredients: [
      { name: '鸡胸肉', amount: '300g' }, { name: '花生米', amount: '80g' },
      { name: '黄瓜', amount: '半根' }, { name: '干辣椒', amount: '8个' },
      { name: '大葱', amount: '1段' }, { name: '生抽', amount: '2勺' },
      { name: '醋', amount: '1.5勺' }, { name: '白糖', amount: '1勺' }, { name: '淀粉', amount: '适量' },
    ],
    steps: [
      '鸡胸肉切成1.5cm小丁，加入1勺生抽、少许淀粉抓匀腌制10分钟。',
      '调碗汁：生抽、醋、白糖、淀粉加少许清水搅匀备用。',
      '热锅凉油，小火把花生米炸香盛出（或用熟花生）。',
      '锅中留底油，下干辣椒、葱段爆香。',
      '倒入鸡丁大火快炒至变色断生。',
      '加入黄瓜丁翻炒，淋入碗汁快速翻炒收汁。',
      '最后撒入花生米翻匀即可出锅。',
    ],
    tips: '鸡丁不要炒太久，变色就够了，久了会柴。碗汁提前调好，下锅手速要快。',
  },
  {
    id: 'mapo-tofu', name: '麻婆豆腐', emoji: '🌶️', cuisine: '川菜', category: '荤菜',
    difficulty: '简单', time: 20, desc: '麻辣鲜香，豆腐嫩滑，一口一个满足。',
    tags: ['豆腐', '猪肉', '豆瓣酱', '葱', '花椒'],
    ingredients: [
      { name: '嫩豆腐', amount: '1盒' }, { name: '猪肉末', amount: '100g' },
      { name: '豆瓣酱', amount: '2勺' }, { name: '花椒粉', amount: '适量' },
      { name: '蒜末', amount: '1勺' }, { name: '葱花', amount: '适量' },
      { name: '生抽', amount: '1勺' }, { name: '淀粉水', amount: '适量' },
    ],
    steps: [
      '豆腐切2cm方块，放入加盐的温水中浸泡5分钟去豆腥（防碎）。',
      '热油下肉末炒至变色出油，盛出一半备用。',
      '下豆瓣酱、蒜末小火炒出红油。',
      '加一碗清水煮开，放入豆腐轻轻推匀，加生抽调味。',
      '中火煮3分钟让豆腐入味，分两次淋入淀粉水勾芡。',
      '撒上肉末、花椒粉和葱花即可。',
    ],
    tips: '推豆腐用锅铲背面轻推，别翻炒，不然容易碎。喜欢麻就多放花椒粉。',
  },
  {
    id: 'yuxiang-rousi', name: '鱼香肉丝', emoji: '🥢', cuisine: '川菜', category: '荤菜',
    difficulty: '中等', time: 25, desc: '酸甜咸辣，没有鱼却有鱼香，经典中的经典。',
    tags: ['猪肉', '胡萝卜', '木耳', '青椒', '豆瓣酱'],
    ingredients: [
      { name: '猪里脊', amount: '250g' }, { name: '胡萝卜', amount: '半根' },
      { name: '木耳', amount: '一把' }, { name: '青椒', amount: '1个' },
      { name: '豆瓣酱', amount: '1.5勺' }, { name: '生抽', amount: '1勺' },
      { name: '醋', amount: '2勺' }, { name: '白糖', amount: '2勺' }, { name: '淀粉', amount: '适量' },
    ],
    steps: [
      '里脊切细丝，加生抽、淀粉腌制10分钟。',
      '胡萝卜、木耳、青椒都切丝备用。',
      '调鱼香汁：醋、白糖、生抽、淀粉、少许水调匀。',
      '热油滑炒肉丝至变色盛出。',
      '底油下豆瓣酱炒出红油，放入配菜丝翻炒。',
      '倒回肉丝，淋入鱼香汁快速翻炒收汁即可。',
    ],
    tips: '糖和醋的比例是鱼香味的灵魂，吃起来要酸甜里带点咸辣。',
  },
  {
    id: 'baizhuo-xia', name: '白灼虾', emoji: '🦐', cuisine: '粤菜', category: '荤菜',
    difficulty: '简单', time: 15, desc: '最大程度保留鲜味，蘸料一拌鲜甜弹牙。',
    tags: ['虾', '姜', '葱'],
    ingredients: [
      { name: '鲜虾', amount: '500g' }, { name: '姜', amount: '3片' },
      { name: '葱', amount: '2根' }, { name: '生抽', amount: '2勺' }, { name: '料酒', amount: '1勺' },
    ],
    steps: [
      '鲜虾剪去虾须，挑出虾线，冲洗干净。',
      '锅中加水，放姜片、葱段、料酒煮开。',
      '水开后下虾，煮到虾身变红弯曲（约2-3分钟）即可捞出。',
      '捞出后过一下冰水，肉质更弹。',
      '调蘸料：生抽加少许姜末，喜欢的可以加点小米辣。',
    ],
    tips: '虾千万别煮老，变红卷起来就立刻捞，过冰水是弹牙的关键。',
  },
  {
    id: 'qingzheng-luyu', name: '清蒸鲈鱼', emoji: '🐟', cuisine: '粤菜', category: '荤菜',
    difficulty: '中等', time: 25, desc: '鱼肉细嫩，原汁原味，鲜得眉毛都要掉了。',
    tags: ['鱼', '姜', '葱'],
    ingredients: [
      { name: '鲈鱼', amount: '1条' }, { name: '姜', amount: '1块' },
      { name: '葱', amount: '3根' }, { name: '蒸鱼豉油', amount: '3勺' }, { name: '料酒', amount: '1勺' },
    ],
    steps: [
      '鲈鱼处理干净，两面划几刀，抹少许料酒和盐去腥。',
      '盘底铺姜片葱段，鱼身上也放一些。',
      '水开后上锅大火蒸8分钟，关火焖2分钟。',
      '取出后倒掉盘里的腥水，挑掉姜葱，重新铺新鲜葱丝。',
      '淋上蒸鱼豉油，最后浇一勺热油激出香味即可。',
    ],
    tips: '蒸鱼时间按大小调整，一斤左右蒸8分钟正好。热油一定要冒烟，香味才出得来。',
  },
  {
    id: 'fanqie-chaodan', name: '番茄炒蛋', emoji: '🍅', cuisine: '家常菜', category: '荤菜',
    difficulty: '简单', time: 10, desc: '国民下饭菜，酸甜可口，三两下就能上桌。',
    tags: ['番茄', '鸡蛋', '葱'],
    ingredients: [
      { name: '番茄', amount: '2个' }, { name: '鸡蛋', amount: '3个' },
      { name: '葱花', amount: '适量' }, { name: '白糖', amount: '1勺' }, { name: '盐', amount: '适量' },
    ],
    steps: [
      '鸡蛋打散加少许盐；番茄切块（怕酸可先去皮）。',
      '热油把蛋液炒成大块嫩蛋，盛出备用。',
      '底油下番茄块，中火炒出汁水，加白糖和盐。',
      '番茄软烂出汁后倒入鸡蛋，翻炒均匀。',
      '撒葱花出锅，喜欢汤汁拌饭可以多留点汁。',
    ],
    tips: '加一勺糖能中和番茄的酸、提鲜。鸡蛋先盛出再合炒，口感更嫩。',
  },
  {
    id: 'tudou-rousi', name: '土豆丝炒肉', emoji: '🥔', cuisine: '家常菜', category: '荤菜',
    difficulty: '简单', time: 20, desc: '酸辣爽脆的土豆丝配上嫩肉，超级下饭。',
    tags: ['土豆', '猪肉', '青椒', '干辣椒'],
    ingredients: [
      { name: '土豆', amount: '2个' }, { name: '猪肉', amount: '150g' },
      { name: '青椒', amount: '1个' }, { name: '干辣椒', amount: '适量' },
      { name: '醋', amount: '1勺' }, { name: '生抽', amount: '1勺' },
    ],
    steps: [
      '土豆切细丝，泡水洗去淀粉，沥干备用。',
      '猪肉切丝，加生抽淀粉腌一下。',
      '热油滑炒肉丝至变色盛出。',
      '底油爆香干辣椒，下土豆丝大火快炒。',
      '土豆丝断生后倒回肉丝，加青椒丝、醋、盐翻炒均匀即可。',
    ],
    tips: '土豆丝一定要泡水去淀粉才会爽脆，临出锅前点醋香味最好。',
  },
  {
    id: 'hongshao-rou', name: '红烧肉', emoji: '🥩', cuisine: '家常菜', category: '荤菜',
    difficulty: '中等', time: 70, desc: '肥而不腻，入口即化，色泽红亮的硬菜。',
    tags: ['五花肉', '姜', '葱'],
    ingredients: [
      { name: '五花肉', amount: '500g' }, { name: '冰糖', amount: '20g' },
      { name: '生抽', amount: '2勺' }, { name: '老抽', amount: '1勺' },
      { name: '料酒', amount: '2勺' }, { name: '姜', amount: '3片' }, { name: '八角', amount: '2个' },
    ],
    steps: [
      '五花肉切麻将块，冷水下锅加料酒焯水，撇去浮沫捞出。',
      '锅中少油下冰糖小火炒出焦糖色（糖色）。',
      '下五花肉翻炒上色，加姜片、八角炒香。',
      '加料酒、生抽、老抽翻匀，加热水没过肉。',
      '大火烧开转小火炖50分钟。',
      '最后大火收汁至浓稠红亮即可。',
    ],
    tips: '炒糖色是颜色好看的关键，小火慢炒别炒糊。炖的时候加热水，别加凉水。',
  },
  {
    id: 'suan-rong-shengcai', name: '蒜蓉生菜', emoji: '🥬', cuisine: '家常菜', category: '素菜',
    difficulty: '简单', time: 8, desc: '清爽解腻，蒜香十足，几分钟搞定的快手菜。',
    tags: ['生菜', '蒜'],
    ingredients: [
      { name: '生菜', amount: '1颗' }, { name: '蒜', amount: '4瓣' },
      { name: '蚝油', amount: '1勺' }, { name: '生抽', amount: '1勺' },
    ],
    steps: [
      '生菜掰开洗净沥干，蒜切末。',
      '热油爆香一半蒜末。',
      '下生菜大火快炒至断生。',
      '加蚝油、生抽快速翻炒。',
      '出锅前撒上另一半生蒜末提香即可。',
    ],
    tips: '全程大火快炒，生菜出水前就要出锅，保持脆嫩。',
  },
  {
    id: 'ganbian-sijidou', name: '干煸四季豆', emoji: '🫛', cuisine: '川菜', category: '素菜',
    difficulty: '中等', time: 20, desc: '外皮焦香起皱，咸香微辣，越嚼越香。',
    tags: ['四季豆', '猪肉', '干辣椒', '蒜'],
    ingredients: [
      { name: '四季豆', amount: '400g' }, { name: '猪肉末', amount: '80g' },
      { name: '干辣椒', amount: '适量' }, { name: '蒜末', amount: '1勺' }, { name: '生抽', amount: '1勺' },
    ],
    steps: [
      '四季豆掐头去筋，洗净沥干水分（一定要干）。',
      '中火热油把四季豆煸炒至表皮起皱发软，盛出。',
      '底油下肉末炒香，加干辣椒、蒜末爆香。',
      '倒回四季豆，加生抽、盐翻炒均匀即可。',
    ],
    tips: '四季豆一定要煸到表皮起皱、内部熟透，没熟的四季豆不能吃。',
  },
  {
    id: 'ditsanxian', name: '地三鲜', emoji: '🍆', cuisine: '家常菜', category: '素菜',
    difficulty: '中等', time: 25, desc: '茄子、土豆、青椒的黄金组合，咸鲜微甜超下饭。',
    tags: ['茄子', '土豆', '青椒', '蒜'],
    ingredients: [
      { name: '茄子', amount: '2个' }, { name: '土豆', amount: '1个' },
      { name: '青椒', amount: '2个' }, { name: '蒜末', amount: '1勺' },
      { name: '生抽', amount: '2勺' }, { name: '白糖', amount: '1勺' }, { name: '淀粉水', amount: '适量' },
    ],
    steps: [
      '茄子、土豆切滚刀块，青椒切块。',
      '土豆块先炸/煎至金黄熟透，再下茄子炸软，盛出沥油。',
      '锅留底油爆香蒜末，下青椒翻炒。',
      '倒入土豆和茄子，加生抽、白糖、少许盐翻炒。',
      '淋入淀粉水勾薄芡，翻匀出锅。',
    ],
    tips: '茄子很吸油，可以先用盐腌一下挤水，或用少油煎制更健康。',
  },
  {
    id: 'xihongshi-jidan-tang', name: '西红柿鸡蛋汤', emoji: '🍲', cuisine: '汤羹', category: '汤品',
    difficulty: '简单', time: 12, desc: '酸甜开胃，蛋花漂亮，暖暖的一碗。',
    tags: ['番茄', '鸡蛋', '葱'],
    ingredients: [
      { name: '番茄', amount: '2个' }, { name: '鸡蛋', amount: '2个' },
      { name: '葱花', amount: '适量' }, { name: '淀粉水', amount: '适量' }, { name: '香油', amount: '几滴' },
    ],
    steps: [
      '番茄切小块，鸡蛋打散。',
      '热油下番茄炒出红汁，加适量清水煮开。',
      '加盐调味，淋入淀粉水让汤微稠。',
      '转圈淋入蛋液，等10秒再轻推成蛋花。',
      '撒葱花、滴几滴香油出锅。',
    ],
    tips: '淋蛋液后别马上搅，等它略凝固再推，蛋花才会又大又漂亮。',
  },
  {
    id: 'zicai-dan-tang', name: '紫菜蛋花汤', emoji: '🥣', cuisine: '汤羹', category: '汤品',
    difficulty: '简单', time: 8, desc: '三分钟快手汤，清淡鲜美，配饭刚刚好。',
    tags: ['紫菜', '鸡蛋', '虾皮', '葱'],
    ingredients: [
      { name: '紫菜', amount: '一小把' }, { name: '鸡蛋', amount: '1个' },
      { name: '虾皮', amount: '1勺' }, { name: '葱花', amount: '适量' }, { name: '香油', amount: '几滴' },
    ],
    steps: [
      '紫菜撕小块放碗里，鸡蛋打散。',
      '锅中加水烧开，放入虾皮煮1分钟。',
      '淋入蛋液，轻轻推成蛋花。',
      '把热汤冲入装紫菜的碗中。',
      '加盐、香油、葱花调味即可。',
    ],
    tips: '紫菜久煮会发黏，用热汤一冲最好，口感最佳。',
  },
  {
    id: 'yumi-paigu-tang', name: '玉米排骨汤', emoji: '🌽', cuisine: '汤羹', category: '汤品',
    difficulty: '简单', time: 80, desc: '清甜滋补，汤鲜肉烂，慢炖出来的温柔。',
    tags: ['排骨', '玉米', '胡萝卜', '姜'],
    ingredients: [
      { name: '排骨', amount: '500g' }, { name: '玉米', amount: '2根' },
      { name: '胡萝卜', amount: '1根' }, { name: '姜', amount: '3片' }, { name: '料酒', amount: '1勺' },
    ],
    steps: [
      '排骨冷水下锅，加料酒焯水去血沫，捞出冲净。',
      '玉米切段，胡萝卜切块。',
      '排骨、姜片放入锅中，加足量清水大火烧开。',
      '转小火炖40分钟，加入玉米和胡萝卜。',
      '继续炖20分钟，出锅前加盐调味即可。',
    ],
    tips: '中途别加凉水，要加就加热水。最后再放盐，肉更容易炖烂。',
  },
  {
    id: 'dan-chao-fan', name: '黄金蛋炒饭', emoji: '🍚', cuisine: '家常菜', category: '主食',
    difficulty: '简单', time: 15, desc: '粒粒分明裹着蛋香，剩饭也能变美味。',
    tags: ['米饭', '鸡蛋', '葱', '胡萝卜'],
    ingredients: [
      { name: '隔夜米饭', amount: '1大碗' }, { name: '鸡蛋', amount: '2个' },
      { name: '葱花', amount: '适量' }, { name: '胡萝卜丁', amount: '适量' }, { name: '生抽', amount: '1勺' },
    ],
    steps: [
      '鸡蛋打散，隔夜饭用手抓散（没有就用新饭摊凉）。',
      '热油倒入蛋液炒散成小块。',
      '倒入米饭，中大火翻炒压散，让饭粒裹上蛋液。',
      '加胡萝卜丁、生抽、盐继续翻炒。',
      '炒到饭粒蹦跳、干香，撒葱花出锅。',
    ],
    tips: '隔夜饭水分少，炒出来才粒粒分明。全程中大火，不停翻炒。',
  },
  {
    id: 'jiachang-chaomian', name: '家常炒面', emoji: '🍜', cuisine: '家常菜', category: '主食',
    difficulty: '简单', time: 20, desc: '酱香浓郁，配菜丰富，一锅就是一顿。',
    tags: ['面条', '鸡蛋', '白菜', '胡萝卜', '火腿'],
    ingredients: [
      { name: '面条', amount: '2人份' }, { name: '鸡蛋', amount: '2个' },
      { name: '白菜', amount: '几片' }, { name: '胡萝卜', amount: '半根' },
      { name: '火腿肠', amount: '1根' }, { name: '生抽', amount: '2勺' }, { name: '老抽', amount: '半勺' },
    ],
    steps: [
      '面条煮至八分熟，过冷水沥干，拌少许油防粘。',
      '鸡蛋炒成块盛出，蔬菜火腿切丝。',
      '热油下蔬菜丝、火腿翻炒。',
      '下面条，加生抽、老抽快速翻炒上色。',
      '倒回鸡蛋翻匀，调味出锅。',
    ],
    tips: '面条提前过冷水拌油不会坨。用筷子配合锅铲翻炒更均匀。',
  },
  {
    id: 'heijiao-yimian', name: '黑椒培根意面', emoji: '🍝', cuisine: '西餐', category: '主食',
    difficulty: '中等', time: 25, desc: '浓郁黑椒奶香，培根咸香，在家也能很西式。',
    tags: ['意面', '培根', '蒜', '黑椒', '洋葱'],
    ingredients: [
      { name: '意大利面', amount: '200g' }, { name: '培根', amount: '3片' },
      { name: '洋葱', amount: '半个' }, { name: '蒜', amount: '2瓣' },
      { name: '黑胡椒', amount: '适量' }, { name: '淡奶油', amount: '100ml' }, { name: '黄油', amount: '10g' },
    ],
    steps: [
      '意面放入加盐沸水煮8-10分钟至弹牙，捞出留一点面汤。',
      '培根切段，洋葱蒜切末。',
      '黄油化开，下蒜末洋葱炒香，加培根煎出油。',
      '倒入淡奶油和少许面汤，加大量黑胡椒煮至微稠。',
      '下意面拌匀，让酱汁裹住面条即可装盘。',
    ],
    tips: '煮面的水要足够咸（像海水）。留点面汤调酱汁，乳化后更顺滑。',
  },
  {
    id: 'huangyou-shujiao', name: '香煎黄油薯角', emoji: '🍟', cuisine: '西餐', category: '素菜',
    difficulty: '简单', time: 30, desc: '外酥里糯，黄油香气十足，追剧最佳拍档。',
    tags: ['土豆', '黑椒'],
    ingredients: [
      { name: '土豆', amount: '2个' }, { name: '黄油', amount: '20g' },
      { name: '黑胡椒', amount: '适量' }, { name: '盐', amount: '适量' }, { name: '迷迭香/孜然', amount: '可选' },
    ],
    steps: [
      '土豆洗净切月牙角，泡水去淀粉后沥干。',
      '冷水下锅煮5分钟至半熟，捞出沥干。',
      '黄油化开，下土豆角中小火慢煎。',
      '煎到各面金黄微焦。',
      '撒盐、黑胡椒（喜欢可加迷迭香或孜然）翻匀出锅。',
    ],
    tips: '先煮半熟再煎，外酥内软。也可以放空气炸锅200度15分钟更省事。',
  },
  {
    id: 'banli-shaoji', name: '板栗烧鸡', emoji: '🌰', cuisine: '粤菜', category: '荤菜',
    difficulty: '中等', time: 50, desc: '板栗粉糯，鸡肉鲜香，咸甜入味的下饭硬菜。',
    tags: ['鸡肉', '板栗', '姜', '葱'],
    ingredients: [
      { name: '鸡腿/鸡块', amount: '500g' }, { name: '板栗', amount: '200g' },
      { name: '姜', amount: '3片' }, { name: '生抽', amount: '2勺' },
      { name: '老抽', amount: '1勺' }, { name: '冰糖', amount: '10g' },
    ],
    steps: [
      '鸡块焯水去血沫捞出。',
      '热锅下少油炒香姜片，下鸡块翻炒至表皮微黄。',
      '加冰糖、生抽、老抽翻炒上色。',
      '加热水没过食材，放入板栗。',
      '大火烧开转小火炖30分钟，最后大火收汁即可。',
    ],
    tips: '板栗提前用热水泡一下好剥壳。收汁别太干，留点汤汁拌饭超香。',
  },
  {
    id: 'mango-banji', name: '芒果班戟', emoji: '🥭', cuisine: '甜点', category: '甜点',
    difficulty: '中等', time: 40, desc: '软糯的皮裹着芒果和奶油，甜甜的像恋爱。',
    tags: ['芒果', '鸡蛋', '牛奶', '淡奶油', '面粉'],
    ingredients: [
      { name: '低筋面粉', amount: '60g' }, { name: '鸡蛋', amount: '1个' },
      { name: '牛奶', amount: '180ml' }, { name: '淡奶油', amount: '200ml' },
      { name: '芒果', amount: '2个' }, { name: '糖', amount: '适量' },
    ],
    steps: [
      '面粉、鸡蛋、牛奶、少许糖混合过筛成面糊，静置20分钟。',
      '不粘锅小火摊成薄饼，放凉备用。',
      '淡奶油加糖打发到硬挺。',
      '芒果切条。',
      '饼皮上放奶油和芒果条，像叠被子一样包成方块，收口朝下即可。',
    ],
    tips: '面糊一定要过筛，饼皮才细腻。包好冷藏一会儿口感更佳。',
  },
  {
    id: 'muxi-bei', name: '木糠杯', emoji: '🍮', cuisine: '甜点', category: '甜点',
    difficulty: '简单', time: 30, desc: '饼干碎配奶油，免烤箱无难度，冷藏一下超好吃。',
    tags: ['淡奶油', '饼干', '炼乳'],
    ingredients: [
      { name: '消化饼干', amount: '100g' }, { name: '淡奶油', amount: '200ml' }, { name: '炼乳', amount: '30g' },
    ],
    steps: [
      '饼干装袋擀压成细碎的木糠状。',
      '淡奶油加炼乳打发至硬挺。',
      '杯子里一层饼干碎一层奶油交替铺。',
      '最上面铺满饼干碎。',
      '冷藏2小时以上再吃，口感最好。',
    ],
    tips: '免烤箱免技术，新手也不会失败。冷藏过的更绵密好吃。',
  },
  {
    id: 'kele-jichi', name: '可乐鸡翅', emoji: '🍯', cuisine: '家常菜', category: '荤菜',
    difficulty: '简单', time: 30, desc: '咸甜入味，色泽红亮，零失败的人气菜。',
    tags: ['鸡翅', '姜', '葱'],
    ingredients: [
      { name: '鸡翅中', amount: '10个' }, { name: '可乐', amount: '1罐' },
      { name: '生抽', amount: '2勺' }, { name: '老抽', amount: '半勺' }, { name: '姜', amount: '3片' },
    ],
    steps: [
      '鸡翅两面划两刀方便入味，冷水焯水去腥捞出。',
      '锅中少油下鸡翅煎至两面金黄。',
      '加姜片、生抽、老抽翻炒上色。',
      '倒入可乐没过鸡翅，大火烧开转中小火。',
      '炖15分钟后大火收汁至浓稠裹汁即可。',
    ],
    tips: '可乐自带糖分就不用额外加糖。收汁时多翻动，别糊锅。',
  },
  {
    id: 'qingjiao-rousi', name: '青椒肉丝', emoji: '🫑', cuisine: '家常菜', category: '荤菜',
    difficulty: '简单', time: 18, desc: '清爽下饭的国民小炒，肉嫩椒香。',
    tags: ['青椒', '猪肉', '蒜', '生抽'],
    ingredients: [
      { name: '猪里脊', amount: '200g' }, { name: '青椒', amount: '3个' },
      { name: '蒜', amount: '2瓣' }, { name: '生抽', amount: '1勺' },
      { name: '料酒', amount: '1勺' }, { name: '淀粉', amount: '适量' },
    ],
    steps: [
      '里脊切丝，加料酒、生抽、淀粉抓匀腌10分钟。',
      '青椒去籽切丝，蒜切片。',
      '热油滑炒肉丝至变色盛出。',
      '底油爆香蒜片，下青椒丝大火翻炒。',
      '倒回肉丝，加盐、生抽翻炒均匀出锅。',
    ],
    tips: '肉丝上点淀粉锁水更嫩，全程大火快炒青椒才翠绿。',
  },
  {
    id: 'suanla-tudousi', name: '酸辣土豆丝', emoji: '🥔', cuisine: '家常菜', category: '素菜',
    difficulty: '简单', time: 15, desc: '爽脆开胃，酸辣过瘾的快手凉热菜。',
    tags: ['土豆', '干辣椒', '蒜', '醋'],
    ingredients: [
      { name: '土豆', amount: '2个' }, { name: '干辣椒', amount: '5个' },
      { name: '蒜', amount: '2瓣' }, { name: '陈醋', amount: '2勺' },
      { name: '花椒', amount: '10粒' }, { name: '盐', amount: '适量' },
    ],
    steps: [
      '土豆切细丝，反复泡水洗去淀粉，沥干。',
      '热油爆香花椒、干辣椒、蒜末。',
      '下土豆丝大火快炒1分钟。',
      '沿锅边淋陈醋，加盐快速翻炒。',
      '土豆丝断生仍脆即可出锅。',
    ],
    tips: '土豆丝一定要泡水去淀粉，醋要沿锅边淋才香。',
  },
  {
    id: 'gualian-baicai', name: '醋溜白菜', emoji: '🥬', cuisine: '家常菜', category: '素菜',
    difficulty: '简单', time: 12, desc: '酸甜爽口，解腻又下饭的家常素菜。',
    tags: ['白菜', '蒜', '醋', '干辣椒'],
    ingredients: [
      { name: '白菜', amount: '半颗' }, { name: '蒜', amount: '2瓣' },
      { name: '干辣椒', amount: '3个' }, { name: '醋', amount: '2勺' },
      { name: '生抽', amount: '1勺' }, { name: '白糖', amount: '1勺' },
    ],
    steps: [
      '白菜帮斜刀片成片，菜叶撕大块，分开放。',
      '热油爆香蒜片、干辣椒。',
      '先下白菜帮翻炒至微软。',
      '再下菜叶，加醋、生抽、白糖大火快炒。',
      '断生出锅，保持脆爽。',
    ],
    tips: '白菜帮和叶分开下锅，帮先炒。醋分两次放更出味。',
  },
  {
    id: 'xihongshi-niunan', name: '番茄炖牛腩', emoji: '🍅', cuisine: '家常菜', category: '荤菜',
    difficulty: '中等', time: 90, desc: '番茄酸甜，牛腩软烂，连汤汁都能拌两碗饭。',
    tags: ['牛腩', '番茄', '土豆', '姜', '葱'],
    ingredients: [
      { name: '牛腩', amount: '500g' }, { name: '番茄', amount: '3个' },
      { name: '土豆', amount: '1个' }, { name: '姜', amount: '3片' },
      { name: '葱', amount: '1根' }, { name: '番茄酱', amount: '2勺' },
    ],
    steps: [
      '牛腩切块冷水下锅焯水，撇沫捞出。',
      '番茄去皮切块，土豆切块。',
      '热油炒香姜葱，下番茄炒出沙，加番茄酱。',
      '放入牛腩翻炒，加热水没过，大火烧开转小火炖60分钟。',
      '加土豆再炖20分钟，加盐收汁即可。',
    ],
    tips: '番茄一半炒成沙做底，一半后放保留果肉口感。',
  },
  {
    id: 'dezhou-paigu', name: '糖醋排骨', emoji: '🍖', cuisine: '家常菜', category: '荤菜',
    difficulty: '中等', time: 45, desc: '酸甜油亮，外焦里嫩，孩子最爱的硬菜。',
    tags: ['排骨', '姜', '醋', '冰糖'],
    ingredients: [
      { name: '肋排', amount: '500g' }, { name: '姜', amount: '3片' },
      { name: '香醋', amount: '3勺' }, { name: '生抽', amount: '2勺' },
      { name: '料酒', amount: '2勺' }, { name: '冰糖', amount: '30g' }, { name: '白芝麻', amount: '少许' },
    ],
    steps: [
      '排骨切段冷水焯水，撇沫捞出沥干。',
      '锅中少油下冰糖小火炒出糖色。',
      '下排骨翻炒上色，加料酒、生抽。',
      '加热水没过排骨，小火炖30分钟。',
      '大火收汁，沿锅边淋香醋，收浓后撒白芝麻。',
    ],
    tips: '糖醋黄金比例：糖、醋、生抽 = 3:2:1。最后淋醋更香。',
  },
  {
    id: 'shousi-baocai', name: '手撕包菜', emoji: '🥬', cuisine: '湘菜', category: '素菜',
    difficulty: '简单', time: 12, desc: '镬气十足，咸香微辣，包菜脆嫩入味。',
    tags: ['包菜', '蒜', '干辣椒', '生抽'],
    ingredients: [
      { name: '包菜', amount: '半颗' }, { name: '蒜', amount: '3瓣' },
      { name: '干辣椒', amount: '5个' }, { name: '生抽', amount: '1勺' },
      { name: '蚝油', amount: '1勺' }, { name: '醋', amount: '半勺' },
    ],
    steps: [
      '包菜用手撕成大片，洗净沥干。',
      '热油爆香蒜片、干辣椒。',
      '下包菜大火猛炒。',
      '加生抽、蚝油、少许醋翻炒。',
      '炒至边缘微焦断生即可出锅。',
    ],
    tips: '一定要大火快炒出镬气，手撕比刀切更入味。',
  },
  {
    id: 'lazi-jiding', name: '辣子鸡丁', emoji: '🌶️', cuisine: '川菜', category: '荤菜',
    difficulty: '中等', time: 35, desc: '麻辣干香，外酥里嫩，越吃越上瘾。',
    tags: ['鸡肉', '干辣椒', '花椒', '蒜', '姜'],
    ingredients: [
      { name: '鸡腿肉', amount: '400g' }, { name: '干辣椒', amount: '一大把' },
      { name: '花椒', amount: '1勺' }, { name: '蒜', amount: '4瓣' },
      { name: '姜', amount: '1块' }, { name: '熟芝麻', amount: '少许' },
    ],
    steps: [
      '鸡腿肉切丁，加料酒、生抽、盐腌15分钟。',
      '热油把鸡丁炸至金黄酥脆，捞出。',
      '锅留底油，下干辣椒、花椒小火炒香。',
      '加姜蒜末炒香，倒入鸡丁大火翻炒。',
      '调味翻匀，撒熟芝麻出锅。',
    ],
    tips: '鸡丁炸两遍更酥。辣椒花椒小火慢炒别炒糊。',
  },
  {
    id: 'shuizhu-roupian', name: '水煮肉片', emoji: '🥩', cuisine: '川菜', category: '荤菜',
    difficulty: '中等', time: 30, desc: '麻辣鲜烫，肉片滑嫩，一锅红油超过瘾。',
    tags: ['猪肉', '豆瓣酱', '豆芽', '生菜', '干辣椒'],
    ingredients: [
      { name: '猪里脊', amount: '300g' }, { name: '豆瓣酱', amount: '2勺' },
      { name: '豆芽', amount: '一把' }, { name: '生菜', amount: '几片' },
      { name: '干辣椒', amount: '适量' }, { name: '花椒', amount: '1勺' }, { name: '蒜末', amount: '2勺' },
    ],
    steps: [
      '里脊切薄片，加盐、料酒、淀粉、蛋清抓匀腌制。',
      '豆芽生菜焯熟垫在碗底。',
      '热油炒香豆瓣酱出红油，加水煮开成汤底。',
      '下肉片煮至变色，连汤倒入碗中。',
      '面上撒蒜末辣椒花椒，浇一勺热油激香。',
    ],
    tips: '肉片上浆要足，水开后下锅，变色即捞别久煮。',
  },
  {
    id: 'guobao-rou', name: '锅包肉', emoji: '🍖', cuisine: '东北菜', category: '荤菜',
    difficulty: '较难', time: 40, desc: '外酥里嫩，酸甜挂汁，东北硬菜代表。',
    tags: ['猪肉', '胡萝卜', '葱', '姜', '醋'],
    ingredients: [
      { name: '猪里脊', amount: '300g' }, { name: '土豆淀粉', amount: '100g' },
      { name: '白糖', amount: '3勺' }, { name: '白醋', amount: '3勺' },
      { name: '胡萝卜丝', amount: '少许' }, { name: '葱姜丝', amount: '适量' },
    ],
    steps: [
      '里脊切大片，加盐料酒腌一下。',
      '土豆淀粉加水调成稠糊，裹满肉片。',
      '油温六成下锅炸定型，捞出复炸至金黄酥脆。',
      '调糖醋汁：白糖、白醋、少许生抽、水。',
      '锅中倒汁烧开，下肉片和葱姜胡萝卜丝快速颠匀出锅。',
    ],
    tips: '复炸是酥脆关键。糖醋汁收浓后下肉片快速翻匀，别久留。',
  },
  {
    id: 'disanxian-dongbei', name: '东北乱炖', emoji: '🥘', cuisine: '东北菜', category: '荤菜',
    difficulty: '简单', time: 50, desc: '一锅炖出豆角土豆五花肉，家的味道。',
    tags: ['五花肉', '豆角', '土豆', '茄子', '玉米'],
    ingredients: [
      { name: '五花肉', amount: '300g' }, { name: '豆角', amount: '200g' },
      { name: '土豆', amount: '2个' }, { name: '茄子', amount: '1个' },
      { name: '玉米', amount: '1根' }, { name: '生抽', amount: '2勺' }, { name: '大酱', amount: '1勺' },
    ],
    steps: [
      '五花肉切块煸炒出油，加葱姜炒香。',
      '加生抽、大酱炒匀。',
      '下豆角、玉米翻炒，加热水。',
      '大火烧开下土豆，中火炖20分钟。',
      '加茄子再炖10分钟，收汁调味即可。',
    ],
    tips: '豆角一定要炖熟透。大酱提味，是东北炖菜的灵魂。',
  },
  {
    id: 'baicai-dunfentiao', name: '猪肉白菜炖粉条', emoji: '🍲', cuisine: '东北菜', category: '荤菜',
    difficulty: '简单', time: 40, desc: '热乎乎一大锅，粉条吸饱汤汁，冬天最爱。',
    tags: ['五花肉', '白菜', '粉条', '葱', '姜'],
    ingredients: [
      { name: '五花肉', amount: '200g' }, { name: '白菜', amount: '半颗' },
      { name: '红薯粉条', amount: '100g' }, { name: '葱姜', amount: '适量' },
      { name: '生抽', amount: '2勺' }, { name: '蚝油', amount: '1勺' },
    ],
    steps: [
      '粉条提前温水泡软。',
      '五花肉切片煸出油，加葱姜炒香。',
      '下白菜帮翻炒变软，加生抽、蚝油。',
      '加热水和白菜叶，烧开后下粉条。',
      '炖10分钟至粉条软糯入味，调味出锅。',
    ],
    tips: '粉条别泡太久，下锅炖才更入味不坨。',
  },
  {
    id: 'duojiao-yutou', name: '剁椒鱼头', emoji: '🐟', cuisine: '湘菜', category: '荤菜',
    difficulty: '中等', time: 35, desc: '鲜辣开胃，鱼肉嫩滑，颜值与味道并存。',
    tags: ['鱼头', '剁椒', '姜', '蒜', '葱'],
    ingredients: [
      { name: '胖头鱼头', amount: '1个' }, { name: '剁椒', amount: '4勺' },
      { name: '姜', amount: '1块' }, { name: '蒜', amount: '4瓣' },
      { name: '葱', amount: '2根' }, { name: '蒸鱼豉油', amount: '2勺' },
    ],
    steps: [
      '鱼头对半剖开洗净，抹料酒和盐去腥。',
      '盘底铺姜片，鱼头摆好。',
      '剁椒加蒜末、少许油拌匀，铺满鱼头。',
      '水开上锅大火蒸10-12分钟。',
      '取出撒葱花，淋蒸鱼豉油，浇热油激香。',
    ],
    tips: '蒸的时间按鱼头大小定，蒸过头肉就老了。',
  },
  {
    id: 'nongjia-xiaochao', name: '农家小炒肉', emoji: '🌶️', cuisine: '湘菜', category: '荤菜',
    difficulty: '简单', time: 20, desc: '辣椒咸香，五花肉焦香，湖南人的下饭神器。',
    tags: ['五花肉', '青椒', '蒜', '豆豉', '生抽'],
    ingredients: [
      { name: '五花肉', amount: '250g' }, { name: '螺丝椒', amount: '5个' },
      { name: '蒜', amount: '3瓣' }, { name: '豆豉', amount: '1勺' },
      { name: '生抽', amount: '1勺' }, { name: '老抽', amount: '半勺' },
    ],
    steps: [
      '五花肉切薄片，青椒切段，蒜切片。',
      '热锅下五花肉煸炒出油至微焦，盛出。',
      '底油下豆豉、蒜片炒香，下青椒煸炒。',
      '倒回五花肉，加生抽、老抽翻炒。',
      '加少许盐炒匀出锅。',
    ],
    tips: '五花肉煸到微焦更香，青椒选辣味足的螺丝椒最地道。',
  },
  {
    id: 'bacai-doufu', name: '家常豆腐', emoji: '🍲', cuisine: '家常菜', category: '荤菜',
    difficulty: '简单', time: 25, desc: '豆腐外焦里嫩，咸鲜微辣，下饭一流。',
    tags: ['豆腐', '猪肉', '青椒', '蒜', '豆瓣酱'],
    ingredients: [
      { name: '老豆腐', amount: '1块' }, { name: '猪肉', amount: '100g' },
      { name: '青椒', amount: '1个' }, { name: '蒜', amount: '2瓣' },
      { name: '豆瓣酱', amount: '1勺' }, { name: '生抽', amount: '1勺' },
    ],
    steps: [
      '豆腐切三角片，煎至两面金黄盛出。',
      '肉片煸炒出油，加蒜、豆瓣酱炒红油。',
      '下青椒翻炒。',
      '放回豆腐，加生抽和少许水焖2分钟。',
      '收汁翻匀出锅。',
    ],
    tips: '豆腐先煎定型再烧不易碎。焖一下更入味。',
  },
  {
    id: 'qingchao-xilanhua', name: '蒜蓉西兰花', emoji: '🥦', cuisine: '家常菜', category: '素菜',
    difficulty: '简单', time: 12, desc: '清淡健康，翠绿爽口，减脂期常备。',
    tags: ['西兰花', '蒜', '蚝油'],
    ingredients: [
      { name: '西兰花', amount: '1颗' }, { name: '蒜', amount: '3瓣' },
      { name: '蚝油', amount: '1勺' }, { name: '盐', amount: '适量' },
    ],
    steps: [
      '西兰花掰小朵，淡盐水泡10分钟洗净。',
      '沸水加盐和油焯30秒，捞出过凉。',
      '热油爆香蒜末。',
      '下西兰花翻炒，加蚝油、盐。',
      '快速炒匀出锅。',
    ],
    tips: '焯水加点油保持翠绿。炒的时间短，避免出水变黄。',
  },
  {
    id: 'ganguo-huacai', name: '干锅花菜', emoji: '🥘', cuisine: '湘菜', category: '素菜',
    difficulty: '简单', time: 20, desc: '花菜吸满五花肉香，咸香微辣超下饭。',
    tags: ['花菜', '五花肉', '青椒', '蒜', '豆瓣酱'],
    ingredients: [
      { name: '有机花菜', amount: '半颗' }, { name: '五花肉', amount: '100g' },
      { name: '青椒', amount: '1个' }, { name: '蒜', amount: '3瓣' },
      { name: '豆瓣酱', amount: '1勺' }, { name: '生抽', amount: '1勺' },
    ],
    steps: [
      '花菜掰小朵，干锅煸炒或焯水至断生。',
      '五花肉煸出油，加蒜、豆瓣酱炒香。',
      '下花菜翻炒，加生抽。',
      '下青椒块翻炒。',
      '炒至花菜微焦入味出锅。',
    ],
    tips: '花菜先煸干水分更香，吸油吸味全靠它。',
  },
  {
    id: 'liangban-huanggua', name: '凉拌黄瓜', emoji: '🥒', cuisine: '家常菜', category: '凉菜',
    difficulty: '简单', time: 8, desc: '爽脆开胃，蒜香十足，夏天必备小凉菜。',
    tags: ['黄瓜', '蒜', '醋', '香油'],
    ingredients: [
      { name: '黄瓜', amount: '2根' }, { name: '蒜', amount: '3瓣' },
      { name: '生抽', amount: '1勺' }, { name: '香醋', amount: '1勺' },
      { name: '香油', amount: '几滴' }, { name: '辣椒油', amount: '可选' },
    ],
    steps: [
      '黄瓜拍裂切段，加盐腌5分钟杀水。',
      '倒掉多余水分，加蒜末。',
      '调入生抽、香醋、香油。',
      '喜欢辣的加辣椒油。',
      '拌匀腌5分钟更入味。',
    ],
    tips: '拍黄瓜比刀切更入味。腌出水倒掉，凉拌才不出汤。',
  },
  {
    id: 'liangban-muer', name: '凉拌木耳', emoji: '🥗', cuisine: '家常菜', category: '凉菜',
    difficulty: '简单', time: 15, desc: '爽滑脆口，酸辣开胃，清爽解腻。',
    tags: ['木耳', '蒜', '小米辣', '香菜', '醋'],
    ingredients: [
      { name: '干木耳', amount: '一把' }, { name: '蒜', amount: '3瓣' },
      { name: '小米辣', amount: '2个' }, { name: '香菜', amount: '少许' },
      { name: '生抽', amount: '2勺' }, { name: '香醋', amount: '2勺' },
    ],
    steps: [
      '木耳提前泡发，洗净撕小朵。',
      '沸水焯2分钟，捞出过凉沥干。',
      '蒜切末、小米辣切圈、香菜切段。',
      '加生抽、香醋、香油、少许糖拌匀。',
      '腌10分钟更入味。',
    ],
    tips: '木耳焯透更安全。冷藏后吃口感更脆爽。',
  },
  {
    id: 'kaoleng-pai', name: '口水鸡', emoji: '🐔', cuisine: '川菜', category: '凉菜',
    difficulty: '中等', time: 35, desc: '皮滑肉嫩，麻辣鲜香，红油诱人口水直流。',
    tags: ['鸡肉', '花椒', '辣椒油', '蒜', '花生'],
    ingredients: [
      { name: '三黄鸡腿', amount: '2个' }, { name: '姜', amount: '3片' },
      { name: '辣椒油', amount: '3勺' }, { name: '花椒粉', amount: '1勺' },
      { name: '蒜末', amount: '2勺' }, { name: '熟花生', amount: '少许' }, { name: '生抽', amount: '2勺' },
    ],
    steps: [
      '鸡腿冷水加姜葱料酒煮15分钟，焖5分钟。',
      '捞出立刻过冰水，让鸡皮更弹。',
      '鸡肉斩块或撕条摆盘。',
      '调料汁：生抽、辣椒油、花椒粉、蒜末、糖、香油。',
      '淋上料汁，撒花生碎、葱花即可。',
    ],
    tips: '煮后过冰水是皮弹肉嫩的关键。料汁可按口味加减麻辣。',
  },
  {
    id: 'xiaomi-zhou', name: '南瓜小米粥', emoji: '🎃', cuisine: '家常菜', category: '早餐',
    difficulty: '简单', time: 30, desc: '香甜软糯，养胃暖身，简单的幸福。',
    tags: ['小米', '南瓜'],
    ingredients: [
      { name: '小米', amount: '1杯' }, { name: '南瓜', amount: '200g' },
      { name: '清水', amount: '适量' },
    ],
    steps: [
      '小米淘洗干净，南瓜切小块。',
      '锅中加足量水烧开，下小米。',
      '加入南瓜块。',
      '中小火熬煮25分钟，期间搅拌防糊底。',
      '熬到粥稠南瓜软烂即可。',
    ],
    tips: '小米冷水还是开水下锅都行，开水下不易糊。南瓜会自然带甜。',
  },
  {
    id: 'jianbing-jidan', name: '鸡蛋灌饼', emoji: '🥪', cuisine: '家常菜', category: '早餐',
    difficulty: '中等', time: 25, desc: '外酥内软，包着嫩蛋和酱，元气满满早餐。',
    tags: ['面粉', '鸡蛋', '生菜', '甜面酱'],
    ingredients: [
      { name: '面粉', amount: '200g' }, { name: '鸡蛋', amount: '2个' },
      { name: '生菜', amount: '几片' }, { name: '甜面酱', amount: '适量' },
      { name: '温水', amount: '110ml' },
    ],
    steps: [
      '面粉加温水和成软面团，醒30分钟。',
      '擀成薄饼，刷油叠层再擀一次。',
      '平底锅小火烙至鼓起，用筷子戳开口。',
      '把打散的蛋液灌入饼中，两面煎熟。',
      '刷甜面酱，夹生菜卷起即可。',
    ],
    tips: '面团越软越好操作。饼鼓起来才好灌蛋液。',
  },
  {
    id: 'huotui-sanmingzhi', name: '元气三明治', emoji: '🥪', cuisine: '西餐', category: '早餐',
    difficulty: '简单', time: 12, desc: '面包夹蛋、生菜、火腿，5分钟搞定的快手早餐。',
    tags: ['吐司', '鸡蛋', '生菜', '火腿', '番茄'],
    ingredients: [
      { name: '吐司', amount: '2片' }, { name: '鸡蛋', amount: '1个' },
      { name: '生菜', amount: '2片' }, { name: '火腿', amount: '2片' },
      { name: '番茄', amount: '2片' }, { name: '沙拉酱', amount: '适量' },
    ],
    steps: [
      '鸡蛋煎成全熟蛋饼。',
      '吐司微烤或直接用，抹沙拉酱。',
      '依次铺生菜、番茄、火腿、煎蛋。',
      '盖上另一片吐司。',
      '对角切开即可。',
    ],
    tips: '吐司稍微烤一下更香脆。配料可随意换成喜欢的。',
  },
  {
    id: 'pijiu-ya', name: '啤酒鸭', emoji: '🦆', cuisine: '家常菜', category: '荤菜',
    difficulty: '中等', time: 60, desc: '啤酒去腥增香，鸭肉软烂入味，超下饭。',
    tags: ['鸭肉', '啤酒', '姜', '青椒', '八角'],
    ingredients: [
      { name: '鸭肉', amount: '半只' }, { name: '啤酒', amount: '1罐' },
      { name: '姜', amount: '4片' }, { name: '青椒', amount: '2个' },
      { name: '八角', amount: '2个' }, { name: '生抽', amount: '2勺' }, { name: '老抽', amount: '1勺' },
    ],
    steps: [
      '鸭肉切块冷水焯水去腥，捞出。',
      '热锅煸炒鸭块至出油微黄。',
      '加姜、八角炒香，加生抽老抽上色。',
      '倒入整罐啤酒没过鸭肉，大火烧开转小火炖40分钟。',
      '加青椒块，大火收汁即可。',
    ],
    tips: '鸭肉先煸炒出油去腥，啤酒代替水炖更香。',
  },
  {
    id: 'baozi-doujiang', name: '皮蛋瘦肉粥', emoji: '🥣', cuisine: '粤菜', category: '早餐',
    difficulty: '简单', time: 40, desc: '绵滑咸香，暖胃舒服，广式经典早餐粥。',
    tags: ['大米', '皮蛋', '猪肉', '姜', '葱'],
    ingredients: [
      { name: '大米', amount: '1杯' }, { name: '皮蛋', amount: '2个' },
      { name: '猪里脊', amount: '150g' }, { name: '姜丝', amount: '少许' },
      { name: '葱花', amount: '适量' }, { name: '盐', amount: '适量' },
    ],
    steps: [
      '大米洗净加少许油盐腌10分钟，更易煮绵。',
      '里脊切丝加生抽淀粉腌一下，皮蛋切丁。',
      '水开下米，大火煮开转小火熬30分钟成稠粥。',
      '下肉丝、一半皮蛋煮5分钟。',
      '加盐调味，撒另一半皮蛋、姜丝、葱花即可。',
    ],
    tips: '米提前用油腌过更绵滑。皮蛋分两次放，口感更丰富。',
  },
  {
    id: 'tang-cu-liji', name: '菠萝咕咾肉', emoji: '🍍', cuisine: '粤菜', category: '荤菜',
    difficulty: '中等', time: 35, desc: '酸甜开胃，外酥里嫩，菠萝果香解腻。',
    tags: ['猪肉', '菠萝', '青椒', '番茄酱'],
    ingredients: [
      { name: '猪里脊', amount: '300g' }, { name: '菠萝', amount: '半个' },
      { name: '青红椒', amount: '各半个' }, { name: '番茄酱', amount: '3勺' },
      { name: '白醋', amount: '1勺' }, { name: '白糖', amount: '2勺' }, { name: '淀粉', amount: '适量' },
    ],
    steps: [
      '里脊切块加盐料酒腌，裹淀粉。',
      '油温六成下锅炸金黄酥脆，复炸一次捞出。',
      '菠萝青红椒切块。',
      '锅中下番茄酱、糖、醋、少许水熬成糖醋汁。',
      '下肉块、菠萝、青红椒快速翻炒裹汁出锅。',
    ],
    tips: '菠萝先用淡盐水泡一下更甜。复炸让肉块更酥脆。',
  },
];

// 收集所有食材标签
function getAllIngredientTags() {
  const set = new Set();
  RECIPES.forEach((r) => (r.tags || []).forEach((t) => set.add(t)));
  return [...set];
}

function getRecipe(id) {
  return RECIPES.find((r) => r.id === id);
}

function randomPhrase() {
  return SWEET_PHRASES[Math.floor(Math.random() * SWEET_PHRASES.length)];
}

module.exports = {
  CUISINES,
  CATEGORIES,
  EMOJI_CHOICES,
  SWEET_PHRASES,
  RECIPES,
  getAllIngredientTags,
  getRecipe,
  randomPhrase,
};
